import "server-only";
import { getSql } from "@/lib/db";
import { logDatabaseError, withDatabaseLogging } from "@/lib/database-error";
import type { AnimalEntry, BreedVariant, Club, Exhibition, Exhibitor,MasterdataHierarchy } from "@/lib/types";

const clubSelect = `SELECT c.id,c.name,coalesce(c.short_name,'') AS short_name,coalesce(c.street,'') AS street,coalesce(c.postal_code,'') AS postal_code,coalesce(c.city,'') AS city,concat_ws(', ',nullif(c.street,''),nullif(concat_ws(' ',c.postal_code,c.city),'')) AS address,coalesce(c.contact_name,'') AS contact_person,coalesce(c.email,'') AS email,coalesce(c.phone,'') AS phone,c.logo_url,c.active,CASE WHEN c.active THEN 'active' WHEN EXISTS(SELECT 1 FROM club_users cu WHERE cu.club_id=c.id AND cu.active=true) THEN 'inactive' ELSE 'blocked' END AS status,c.created_at::text AS created_at FROM clubs c`;
const showSelect = `SELECT s.id,s.club_id,coalesce(c.short_name,'') AS club_name,s.name AS title,coalesce(s.venue_name,'') AS venue,concat_ws(', ',nullif(s.venue_street,''),nullif(concat_ws(' ',s.venue_postal_code,s.venue_city),'')) AS venue_address,coalesce(s.venue_street,'') AS venue_street,coalesce(s.venue_postal_code,'') AS venue_postal_code,coalesce(s.venue_city,'') AS venue_city,coalesce(s.show_start::text,'') AS starts_at,coalesce(s.show_end::text,'') AS ends_at,coalesce(s.delivery_at::text,'') AS delivery_at,coalesce(s.judging_at::text,'') AS judging_at,coalesce(s.collection_at::text,'') AS collection_at,s.registration_deadline::text AS registration_deadline,s.status,s.public_slug,coalesce(s.subtitle,'') AS description,(SELECT count(*)::int FROM exhibitors x WHERE x.show_id=s.id) AS exhibitor_count,(SELECT count(*)::int FROM animals a WHERE a.show_id=s.id) AS animal_count,s.created_at::text AS created_at FROM shows s JOIN clubs c ON c.id=s.club_id`;
const exhibitorSelect = `SELECT x.id,x.show_id,s.name AS show_title,s.club_id,c.short_name AS club_name,x.first_name,x.last_name,x.street,''::text AS house_number,x.postal_code,x.city,x.email,x.phone,coalesce(x.exhibitor_club_name,'') AS association_name,NULL::text AS membership_number,coalesce(x.age_group,'') AS age_group,x.created_at::text AS created_at FROM exhibitors x JOIN shows s ON s.id=x.show_id JOIN clubs c ON c.id=s.club_id`;
const animalSelect = `SELECT a.id,a.entry_id,a.show_id AS exhibition_id,s.name AS exhibition_title,e.exhibitor_id,x.first_name||' '||x.last_name AS exhibitor_name,a.breed_color_variant_id AS breed_variant_id,coalesce(a.entry_type,'') AS species,b.name AS breed,cv.name AS color,coalesce(a.sex,'unbekannt') AS sex,extract(year from current_date)::int AS birth_year,coalesce(a.age_class,'') AS age_class,coalesce(a.ring_number,'') AS ring_number,a.cage_number,coalesce(e.total_amount,0)::text AS entry_fee,e.status,a.created_at::text AS created_at FROM animals a JOIN entries e ON e.id=a.entry_id JOIN shows s ON s.id=a.show_id JOIN exhibitors x ON x.id=e.exhibitor_id JOIN breed_color_variants bcv ON bcv.id=a.breed_color_variant_id JOIN breeds b ON b.id=bcv.breed_id JOIN color_variants cv ON cv.id=bcv.color_variant_id`;

export async function getCounts(clubId:string){const sql=getSql();const[shows,exhibitors,animals]=await Promise.all([withDatabaseLogging("dashboard.count.shows",()=>sql`SELECT count(*)::int AS count FROM shows WHERE club_id=${clubId}`),withDatabaseLogging("dashboard.count.exhibitors",()=>sql`SELECT count(*)::int AS count FROM exhibitors x JOIN shows s ON s.id=x.show_id WHERE s.club_id=${clubId}`),withDatabaseLogging("dashboard.count.animals",()=>sql`SELECT count(*)::int AS count FROM animals a JOIN shows s ON s.id=a.show_id WHERE s.club_id=${clubId}`)]);return{exhibitions:Number(shows[0].count),exhibitors:Number(exhibitors[0].count),entries:Number(animals[0].count)}}
const emptyCounts={exhibitions:0,exhibitors:0,entries:0};
export async function getDashboardData(clubId:string){const[countsResult,showsResult]=await Promise.allSettled([getCounts(clubId),getExhibitions(clubId)]);if(countsResult.status==="rejected")logDatabaseError("dashboard.counts.fallback",countsResult.reason);if(showsResult.status==="rejected")logDatabaseError("dashboard.shows.fallback",showsResult.reason);return{counts:countsResult.status==="fulfilled"?countsResult.value:emptyCounts,exhibitions:showsResult.status==="fulfilled"?showsResult.value:[]}}
export async function getClubs(){return await withDatabaseLogging("clubs.list",async()=>await getSql().query(`${clubSelect} ORDER BY name`) as Club[])}
export async function getOperatorSummary(){const rows=await withDatabaseLogging("operator.summary",()=>getSql()`SELECT count(*)::int AS total,count(*) FILTER(WHERE c.active)::int AS active,count(*) FILTER(WHERE NOT c.active AND EXISTS(SELECT 1 FROM club_users cu WHERE cu.club_id=c.id AND cu.active=true))::int AS inactive,count(*) FILTER(WHERE NOT c.active AND NOT EXISTS(SELECT 1 FROM club_users cu WHERE cu.club_id=c.id AND cu.active=true))::int AS blocked FROM clubs c`);const row=rows[0];return{total:Number(row.total),active:Number(row.active),inactive:Number(row.inactive),blocked:Number(row.blocked)}}
export async function getActiveClubs(){return await withDatabaseLogging("clubs.active",async()=>await getSql().query(`${clubSelect} WHERE active=true ORDER BY name`) as Club[])}
export async function getClub(id:string){const rows=await withDatabaseLogging("clubs.detail",async()=>await getSql().query(`${clubSelect} WHERE id=$1`,[id]) as Club[]);return rows[0]}
export async function getExhibitions(clubId:string){return await withDatabaseLogging("shows.list",async()=>await getSql().query(`${showSelect} WHERE s.club_id=$1 ORDER BY s.show_start DESC NULLS LAST`,[clubId]) as Exhibition[])}
export async function getExhibition(id:string,clubId:string){const rows=await withDatabaseLogging("shows.detail",async()=>await getSql().query(`${showSelect} WHERE s.id=$1 AND s.club_id=$2`,[id,clubId]) as Exhibition[]);return rows[0]}
export async function getExhibitors(clubId:string,search=""){const term=`%${search}%`;const searchFilter=search?" AND (x.first_name ILIKE $2 OR x.last_name ILIKE $2 OR x.city ILIKE $2 OR x.exhibitor_club_name ILIKE $2 OR x.email ILIKE $2)":"";return await withDatabaseLogging("exhibitors.list",async()=>await getSql().query(`${exhibitorSelect} WHERE s.club_id=$1${searchFilter} ORDER BY x.last_name,x.first_name`,search?[clubId,term]:[clubId]) as Exhibitor[])}
export async function getExhibitor(id:string,clubId:string){const rows=await withDatabaseLogging("exhibitors.detail",async()=>await getSql().query(`${exhibitorSelect} WHERE x.id=$1 AND s.club_id=$2`,[id,clubId]) as Exhibitor[]);return rows[0]}
export async function getEntries(clubId:string,search="",exhibitionId=""){const conditions:string[]=["s.club_id=$1"];const params:string[]=[clubId];if(exhibitionId){params.push(exhibitionId);conditions.push(`a.show_id=$${params.length}`)}if(search){params.push(`%${search}%`);conditions.push(`(b.name ILIKE $${params.length} OR a.ring_number ILIKE $${params.length} OR x.first_name ILIKE $${params.length} OR x.last_name ILIKE $${params.length})`)}return await withDatabaseLogging("animals.list",async()=>await getSql().query(`${animalSelect} WHERE ${conditions.join(" AND ")} ORDER BY a.created_at DESC`,params) as AnimalEntry[])}
export async function getEntry(id:string,clubId:string){const rows=await withDatabaseLogging("animals.detail",async()=>await getSql().query(`${animalSelect} WHERE a.id=$1 AND s.club_id=$2`,[id,clubId]) as AnimalEntry[]);return rows[0]}
export async function getBreedVariants(){return await withDatabaseLogging("breed-variants.list",async()=>await getSql()`SELECT bcv.id,b.name AS breed,cv.name AS color FROM breed_color_variants bcv JOIN breeds b ON b.id=bcv.breed_id JOIN color_variants cv ON cv.id=bcv.color_variant_id WHERE bcv.active=true AND b.active=true AND cv.active=true ORDER BY b.name,cv.name` as BreedVariant[])}
export async function getMasterdataSummary(){const rows=await getSql()`SELECT (SELECT count(*)::int FROM animal_categories WHERE active=true) AS categories,(SELECT count(*)::int FROM breed_groups WHERE active=true) AS groups,(SELECT count(*)::int FROM breeds WHERE active=true) AS breeds,(SELECT count(*)::int FROM color_variants WHERE active=true) AS colors,(SELECT count(*)::int FROM breed_color_variants WHERE active=true) AS combinations,(SELECT max(imported_at)::text FROM masterdata_imports) AS last_import,(SELECT file_name FROM masterdata_imports ORDER BY imported_at DESC LIMIT 1) AS source_version`;const row=rows[0];return{categories:Number(row.categories),groups:Number(row.groups),breeds:Number(row.breeds),colors:Number(row.colors),combinations:Number(row.combinations),lastImport:row.last_import?String(row.last_import):null,sourceVersion:row.source_version?String(row.source_version):null}}
export async function getMasterdataHierarchy():Promise<MasterdataHierarchy>{const sql=getSql(),[categories,groups,breeds,colors]=await Promise.all([sql`SELECT id::text,name FROM animal_categories WHERE active=true ORDER BY sort_order,name`,sql`SELECT id::text,name,category_id::text AS parent_id FROM breed_groups WHERE active=true ORDER BY sort_order,name`,sql`SELECT id::text,name,breed_group_id::text AS parent_id FROM breeds WHERE active=true ORDER BY sort_order,name`,sql`SELECT cv.id::text,cv.name,bcv.breed_id::text AS parent_id,bcv.id::text AS variant_id FROM breed_color_variants bcv JOIN color_variants cv ON cv.id=bcv.color_variant_id WHERE bcv.active=true AND cv.active=true ORDER BY bcv.standard_sort_order,cv.name`]);return{categories,groups,breeds,colors} as MasterdataHierarchy}
export async function getPublicShow(slug:string){const rows=await getSql()`SELECT s.id::text,s.club_id::text,s.name AS title,coalesce(s.venue_name,'') AS venue,s.registration_deadline::text,s.status,c.name AS club_name,c.active AS club_active FROM shows s JOIN clubs c ON c.id=s.club_id WHERE s.public_slug=${slug}`;return rows[0] as undefined|{id:string;club_id:string;title:string;venue:string;registration_deadline:string;status:string;club_name:string;club_active:boolean}}
export async function getPublicConfirmation(slug:string,token:string){const rows=await getSql()`SELECT e.id::text,e.registration_number,e.status,e.submitted_at::text,x.first_name,x.last_name,x.email,x.city,s.name AS show_title FROM entries e JOIN shows s ON s.id=e.show_id JOIN exhibitors x ON x.id=e.exhibitor_id WHERE s.public_slug=${slug} AND e.management_token::text=${token}`;if(!rows[0])return null;const animals=await getSql()`SELECT b.name AS breed,cv.name AS color,a.sex,coalesce(a.age_class,'') AS age_class,coalesce(a.ring_number,'') AS ring_number FROM animals a JOIN entries e ON e.id=a.entry_id JOIN breed_color_variants bcv ON bcv.id=a.breed_color_variant_id JOIN breeds b ON b.id=bcv.breed_id JOIN color_variants cv ON cv.id=bcv.color_variant_id WHERE e.management_token::text=${token} ORDER BY a.created_at`;return{entry:rows[0],animals}}
