import "server-only";
import PDFDocument from "pdfkit";
import type {DocumentEntry,ShowDocumentData} from "@/lib/show-documents";
import {catalogChecks} from "@/lib/show-documents";

const euro=(value:string)=>`${Number(value).toFixed(2).replace(".",",")} EUR`;
const date=(value:string)=>new Date(value).toLocaleDateString("de-DE");
const age=(value:string)=>value==="young"?"jung":value==="old"?"alt":"gemischt";

function collect(doc:PDFKit.PDFDocument){return new Promise<Buffer>((resolve,reject)=>{const chunks:Buffer[]=[];doc.on("data",chunk=>chunks.push(Buffer.from(chunk)));doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject)})}
function line(doc:PDFKit.PDFDocument,y:number){doc.moveTo(42,y).lineTo(doc.page.width-42,y).strokeColor("#999999").lineWidth(.5).stroke()}
function showHeader(doc:PDFKit.PDFDocument,data:ShowDocumentData,entry:DocumentEntry,continued=false){doc.font("Helvetica-Bold").fontSize(16).fillColor("#111111").text("B-Bogen",42,38,{align:"right"});doc.fontSize(15).text(data.show.title,42,38,{width:380});doc.font("Helvetica").fontSize(9).text(`${data.show.club_name} | ${data.show.venue} | ${date(data.show.starts_at)} - ${date(data.show.ends_at)}`,42,59);line(doc,76);doc.font("Helvetica-Bold").fontSize(11).text(`${entry.last_name}, ${entry.first_name}${entry.age_group==="youth"?" (Jugend)":""}`,42,88);doc.font("Helvetica").fontSize(9).text(`${entry.street} ${entry.house_number} | ${entry.postal_code} ${entry.city} | Verein: ${entry.association_name||"-"}`,42,105);doc.text(`Ausstellernummer: ${entry.exhibitor_number??"fehlt"} | Meldungsnummer: ${entry.registration_number}${continued?" | Fortsetzung":""}`,42,120);line(doc,137)}
function animalTableHeader(doc:PDFKit.PDFDocument,y:number){doc.font("Helvetica-Bold").fontSize(8);const heads=[["Käfig",42,42],["Rasse",84,130],["Farbenschlag",214,145],["G",359,34],["Alter",393,42],["Ringnummer",435,115]] as const;for(const[h,x,w]of heads)doc.text(h,x,y,{width:w});line(doc,y+13);return y+18}
function ensureBPage(doc:PDFKit.PDFDocument,data:ShowDocumentData,entry:DocumentEntry,y:number,needed:number){if(y+needed<doc.page.height-48)return y;doc.addPage();showHeader(doc,data,entry,true);return animalTableHeader(doc,151)}

export async function createBFormsPdf(data:ShowDocumentData,onlyEntryId?:string){
  const entries=onlyEntryId?data.entries.filter(entry=>entry.id===onlyEntryId):data.entries;
  const doc=new PDFDocument({size:"A4",margin:42,autoFirstPage:false,info:{Title:`B-Bögen ${data.show.title}`,Author:data.show.club_name}}),result=collect(doc);
  for(const entry of entries){doc.addPage();showHeader(doc,data,entry);let y=animalTableHeader(doc,151);doc.font("Helvetica").fontSize(8);for(const animal of entry.animals){y=ensureBPage(doc,data,entry,y,18);doc.text(String(animal.catalog_number??animal.cage_number??"-"),42,y,{width:42});doc.text(animal.breed,84,y,{width:130});doc.text(animal.color||"-",214,y,{width:145});doc.text(animal.sex,359,y,{width:34});doc.text(age(animal.age_class),393,y,{width:42});doc.text(animal.ring_number||"-",435,y,{width:115});y+=18}y=ensureBPage(doc,data,entry,y,165);line(doc,y);y+=12;doc.font("Helvetica-Bold").fontSize(10).text("Kostenaufstellung",42,y);y+=17;doc.font("Helvetica").fontSize(8);for(const fee of entry.fees){doc.text(`${fee.quantity} x ${euro(fee.unit_amount)} | ${fee.description}`,42,y,{width:350});doc.text(euro(fee.total_amount),420,y,{width:130,align:"right"});y+=14}doc.font("Helvetica-Bold").text(`Gesamt: ${euro(entry.total_amount)}   Bezahlt: ${euro(entry.paid_amount)}   Rest: ${euro(entry.remaining_amount)}`,42,y,{width:508,align:"right"});y+=27;line(doc,y);y+=12;doc.font("Helvetica").fontSize(8).text("Bemerkungen: _________________________________________________________________",42,y);y+=22;doc.text("Zahlung bestätigt: __________________   Ausgabe/Abholung: __________________",42,y);y+=28;doc.text("Unterschrift Aussteller: _________________________________________________",42,y)}
  if(entries.length===0){doc.addPage();doc.fontSize(14).text("Keine B-Bögen verfügbar.",42,50)}doc.end();return result;
}

function rawHeader(doc:PDFKit.PDFDocument,data:ShowDocumentData){doc.font("Helvetica-Bold").fontSize(17).text(`Rohkatalog - ${data.show.title}`,42,35);doc.font("Helvetica").fontSize(9).text(`${data.show.club_name} | ${data.show.venue} | ${date(data.show.starts_at)} - ${date(data.show.ends_at)}`,42,58);line(doc,75)}
function rawColumns(doc:PDFKit.PDFDocument,y:number){doc.font("Helvetica-Bold").fontSize(7.5);const heads=[["Käfig",42,42],["Geschl.",84,42],["Alter",126,45],["Ringnummer",171,105],["Ausst.-Nr.",276,55],["Aussteller",331,180]] as const;for(const[h,x,w]of heads)doc.text(h,x,y,{width:w});line(doc,y+12);return y+17}
function ensureRawPage(doc:PDFKit.PDFDocument,data:ShowDocumentData,y:number,needed:number){if(y+needed<doc.page.height-38)return y;doc.addPage();return rawColumns(doc,89)}

export async function createRawCatalogPdf(data:ShowDocumentData){const doc=new PDFDocument({size:"A4",layout:"landscape",margin:42,autoFirstPage:false,info:{Title:`Rohkatalog ${data.show.title}`,Author:data.show.club_name}}),result=collect(doc);doc.on("pageAdded",()=>rawHeader(doc,data));doc.addPage();const checks=catalogChecks(data.animals);doc.font("Helvetica-Bold").fontSize(10).text("Katalogprüfung",42,88);doc.font("Helvetica").fontSize(8).text(`${checks.total} Tiere | ${checks.withoutCage} ohne Käfignummer | ${checks.duplicateCages} doppelte Käfignummern | ${checks.withoutRing} fehlende Ringnummern | ${checks.withoutColor} ohne Farbenschlag`,42,104);let y=rawColumns(doc,126),lastCategory="",lastBreed="",lastColor="";for(const animal of data.animals){if(animal.category!==lastCategory){y=ensureRawPage(doc,data,y,35);doc.font("Helvetica-Bold").fontSize(12).text(animal.category.toUpperCase(),42,y);y+=20;lastCategory=animal.category;lastBreed="";lastColor=""}if(animal.breed!==lastBreed||animal.color!==lastColor){y=ensureRawPage(doc,data,y,30);doc.font("Helvetica-Bold").fontSize(9).text(`${animal.breed} - ${animal.color||"ohne Farbenschlag"}`,42,y);y+=17;lastBreed=animal.breed;lastColor=animal.color}y=ensureRawPage(doc,data,y,15);doc.font("Helvetica").fontSize(7.5);doc.text(String(animal.catalog_number??animal.cage_number??"FEHLT"),42,y,{width:42});doc.text(animal.sex||"FEHLT",84,y,{width:42});doc.text(age(animal.age_class),126,y,{width:45});doc.text(animal.ring_number||"FEHLT",171,y,{width:105});doc.text(String(animal.exhibitor_number??"-"),276,y,{width:55});doc.text(animal.exhibitor_name,331,y,{width:180});y+=14}doc.end();return result}
