import Link from "next/link";
import {notFound} from "next/navigation";
import {ArrowLeft,FileText,Pencil,Plus,Trash2} from "lucide-react";
import {cancelAnimal,changeEntryStatus,updateEntryPayment} from "@/app/actions";
import {Status} from "@/components/ui";
import {requireActiveClub} from "@/lib/club-context";
import {getManagedEntryByExhibitor} from "@/lib/data";

const euro=(value:string)=>Number(value).toLocaleString("de-DE",{style:"currency",currency:"EUR"});
const statusLabels:Record<string,string>={received:"Eingegangen",reviewed:"Geprüft",question:"Rückfrage",cancelled:"Storniert"};
export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{id:string}>}){
  const [{id},club]=await Promise.all([params,requireActiveClub()]),record=await getManagedEntryByExhibitor(id,club.id);
  if(!record)notFound();
  const {entry,animals,fees}=record;
  return <><div className="detail-actions"><Link className="button secondary" href="/aussteller"><ArrowLeft size={17}/>Zur Liste</Link><a className="button secondary" href={`/api/ausstellungen/${entry.show_id}/b-boegen?meldung=${entry.id}`} target="_blank"><FileText size={16}/>B-Bogen</a><Link className="button primary" href={`/aussteller/${id}/bearbeiten`}><Pencil size={16}/>Kontaktdaten bearbeiten</Link></div>
    <div className="page-header"><div><h1>{entry.first_name} {entry.last_name}</h1><p>Ausstellernr. {entry.exhibitor_number??"noch nicht vergeben"} · Meldung {entry.registration_number}</p></div><Status>{statusLabels[entry.workflow_status]}</Status></div>
    <section className="detail-grid"><div className="detail-card"><h2>Ausstellerdaten</h2><div className="facts"><div className="fact"><span>Anschrift</span><strong>{entry.street} {entry.house_number}<br/>{entry.postal_code} {entry.city}</strong></div><div className="fact"><span>Kontakt</span><strong>{entry.email||"–"}<br/>{entry.phone||"–"}</strong></div><div className="fact"><span>TSK-/Betriebsnummer</span><strong>{entry.livestock_number||"–"}</strong></div><div className="fact"><span>Verein / Altersgruppe</span><strong>{entry.association_name||"–"} · {entry.age_group==="youth"?"Jugend":"Erwachsene"}</strong></div><div className="fact"><span>Ausstellung</span><strong>{entry.show_title}</strong></div><div className="fact"><span>Meldedatum</span><strong>{new Date(entry.submitted_at).toLocaleString("de-DE")}</strong></div></div></div>
      <aside className="detail-card"><h2>Meldung & Zahlung</h2><div className="facts single"><div className="fact"><span>Meldeobjekte</span><strong>{entry.single_count} Einzel · {entry.stem_count} Stämme · {entry.aviary_count} Volieren</strong></div><div className="fact"><span>Gesamt / bezahlt / Rest</span><strong>{euro(entry.total_amount)} / {euro(entry.paid_amount)} / {euro(entry.remaining_amount)}</strong></div><div className="fact"><span>Zahlungsdatum / Art</span><strong>{entry.paid_at?new Date(entry.paid_at).toLocaleDateString("de-DE"):"–"} · {entry.payment_method||"–"}</strong></div></div><form action={updateEntryPayment} className="inline-editor"><input type="hidden" name="entryId" value={entry.id}/><input name="paidAmount" type="number" min="0" step="0.01" defaultValue={entry.paid_amount}/><select name="paymentStatus" defaultValue={entry.payment_status}><option value="open">Offen</option><option value="partial">Teilbezahlt</option><option value="paid">Bezahlt</option></select><select name="paymentMethod" defaultValue={entry.payment_method??""}><option value="">Keine Zahlungsart</option><option value="cash">Bar</option><option value="transfer">Überweisung</option><option value="other">Sonstige</option></select><button className="button secondary">Zahlung speichern</button></form><form action={changeEntryStatus} className="inline-editor"><input type="hidden" name="entryId" value={entry.id}/><select name="status" defaultValue={entry.workflow_status}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="button secondary">Status speichern</button></form></aside></section>
    <section className="detail-card section-card"><h2>Kostenaufstellung</h2><div className="cost-lines">{fees.map(fee=><div key={fee.id}><span>{fee.quantity} × {euro(fee.unit_amount)} · {fee.description}</span><strong>{euro(fee.total_amount)}</strong></div>)}<div className="cost-total"><span>Gesamt</span><strong>{euro(entry.total_amount)}</strong></div></div></section>
    <section className="detail-card section-card"><div className="section-heading"><h2>Gemeldete Tiere</h2><Link className="button primary" href={`/aussteller/${id}/tier-neu`}><Plus size={16}/>Tier ergänzen</Link></div><div className="table-wrap"><table><thead><tr><th>Käfig</th><th>Kategorie</th><th>Rasse / Farbenschlag</th><th>Geschlecht / Alter</th><th>Ringnummer</th><th>Status</th><th/></tr></thead><tbody>{animals.map(animal=><tr key={animal.id}><td>{animal.catalog_number??animal.cage_number??"–"}</td><td>{animal.category}</td><td><strong>{animal.breed}</strong><span className="sub">{animal.color}</span></td><td>{animal.sex} · {animal.age_class}</td><td>{animal.ring_number||"–"}</td><td><Status>{animal.withdrawn?"Storniert":"Aktiv"}</Status></td><td><div className="row-actions"><Link className="icon-button" href={`/tiermeldungen/${animal.id}/bearbeiten`} title="Bearbeiten"><Pencil size={15}/></Link>{!animal.withdrawn?<form action={cancelAnimal}><input type="hidden" name="animalId" value={animal.id}/><button className="icon-button danger" title="Tier stornieren"><Trash2 size={15}/></button></form>:null}</div></td></tr>)}</tbody></table></div></section>
  </>;
}
