import Link from "next/link";
import {Check,ExternalLink} from "lucide-react";
import {assignExhibitorNumbers,changeEntryStatus,markEntryPaid} from "@/app/actions";
import {EmptyState,PageHeader,Status} from "@/components/ui";
import {requireActiveClub} from "@/lib/club-context";
import {getExhibitions,getManagedEntries} from "@/lib/data";

const statusLabels:Record<string,string>={received:"Eingegangen",reviewed:"Geprüft",question:"Rückfrage",cancelled:"Storniert"};
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;ausstellung?:string;status?:string}>}){
  const club=await requireActiveClub(),filters=await searchParams;
  const [rows,shows]=await Promise.all([getManagedEntries(club.id,{q:filters.q,showId:filters.ausstellung,status:filters.status}),getExhibitions(club.id)]);
  return <><PageHeader title="Aussteller" description={`Eingegangene Meldungen von ${club.short_name}`}/>
    <form className="toolbar management-toolbar"><input className="search" name="q" placeholder="Name, Ort, Verein, Meldungsnr. …" defaultValue={filters.q}/><select name="ausstellung" defaultValue={filters.ausstellung}><option value="">Alle Ausstellungen</option>{shows.map(show=><option key={show.id} value={show.id}>{show.title}</option>)}</select><select name="status" defaultValue={filters.status}><option value="">Alle Status</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="button secondary">Filtern</button><Link className="button secondary" href="/aussteller">Zurücksetzen</Link></form>
    <div className="management-tools">{shows.map(show=><form action={assignExhibitorNumbers} key={show.id}><input type="hidden" name="showId" value={show.id}/><input name="start" type="number" min="1" defaultValue="1" aria-label="Startnummer"/><button className="button secondary">Ausstellernummern · {show.title}</button></form>)}</div>
    {rows.length===0?<EmptyState title="Keine Meldungen" text="Für diesen Filter liegen keine Meldungen vor."/>:<div className="table-card"><div className="table-wrap"><table className="management-table"><thead><tr><th>Nr.</th><th>Name / Ort</th><th>Verein</th><th>Meldung</th><th>Tiere</th><th>Gesamt</th><th>Zahlung</th><th>Status</th><th>Aktionen</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.exhibitor_number??"–"}</td><td><strong>{row.last_name}, {row.first_name}</strong><span className="sub">{row.postal_code} {row.city}</span></td><td>{row.association_name||"–"}</td><td>{row.registration_number}<span className="sub">{row.show_title}</span></td><td>{row.animal_count}</td><td>{Number(row.total_amount).toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</td><td><Status>{row.payment_status}</Status><span className="sub">Rest {Number(row.remaining_amount).toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</span></td><td><Status>{statusLabels[row.workflow_status]}</Status></td><td><div className="compact-actions"><Link className="icon-button" href={`/aussteller/${row.exhibitor_id}`} title="Öffnen"><ExternalLink size={15}/></Link>{row.payment_status!=="paid"?<form action={markEntryPaid}><input type="hidden" name="entryId" value={row.id}/><button className="icon-button" title="Bezahlt markieren"><Check size={15}/></button></form>:null}<form action={changeEntryStatus}><input type="hidden" name="entryId" value={row.id}/><select name="status" defaultValue={row.workflow_status} aria-label="Meldestatus" onChange={undefined}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="button secondary small">Speichern</button></form></div></td></tr>)}</tbody></table></div></div>}
  </>;
}
