import Link from "next/link";
import {Pencil} from "lucide-react";
import {assignCageNumbers} from "@/app/actions";
import {EmptyState,PageHeader,Status} from "@/components/ui";
import {requireActiveClub} from "@/lib/club-context";
import {getExhibitions,getManagedAnimals,getMasterdataHierarchy} from "@/lib/data";

export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;ausstellung?:string;kategorie?:string;rasse?:string;farbe?:string;geschlecht?:string;alter?:string;status?:string}>}){
  const club=await requireActiveClub(),f=await searchParams;
  const [rows,shows,masterdata]=await Promise.all([getManagedAnimals(club.id,{q:f.q,showId:f.ausstellung,category:f.kategorie,breed:f.rasse,color:f.farbe,sex:f.geschlecht,age:f.alter,status:f.status}),getExhibitions(club.id),getMasterdataHierarchy()]);
  return <><PageHeader title="Tiermeldungen" description={`Fachlich sortierte Arbeitsliste für ${club.name}`}/><form className="toolbar management-toolbar animal-filters"><input className="search" name="q" placeholder="Aussteller, Ring- oder Käfignummer …" defaultValue={f.q}/><select name="ausstellung" defaultValue={f.ausstellung}><option value="">Alle Ausstellungen</option>{shows.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><select name="kategorie" defaultValue={f.kategorie}><option value="">Alle Kategorien</option>{masterdata.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="rasse" defaultValue={f.rasse}><option value="">Alle Rassen</option>{masterdata.breeds.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select name="farbe" defaultValue={f.farbe}><option value="">Alle Farbenschläge</option>{masterdata.colors.map(x=><option key={`${x.parent_id}-${x.id}`} value={x.id}>{x.name}</option>)}</select><select name="geschlecht" defaultValue={f.geschlecht}><option value="">Alle Geschlechter</option><option value="1,0">1,0</option><option value="0,1">0,1</option><option value="mixed">gemischt</option></select><select name="alter" defaultValue={f.alter}><option value="">Alle Altersklassen</option><option value="young">jung</option><option value="old">alt</option><option value="mixed">gemischt</option></select><select name="status" defaultValue={f.status}><option value="">Alle Status</option><option value="active">aktiv</option><option value="cancelled">storniert</option></select><button className="button secondary">Filtern</button><Link className="button secondary" href="/tiermeldungen">Zurücksetzen</Link></form>
    <div className="management-tools">{shows.map(show=><form action={assignCageNumbers} key={show.id}><input type="hidden" name="showId" value={show.id}/><input name="start" type="number" min="1" defaultValue="1" aria-label="Startnummer"/><button className="button secondary">Käfignummern · {show.title}</button></form>)}</div>
    {rows.length===0?<EmptyState title="Keine Tiermeldungen" text="Für diesen Filter liegen keine Tiere vor."/>:<div className="table-card"><div className="table-wrap"><table className="management-table"><thead><tr><th>Käfig</th><th>Ausstellernr.</th><th>Aussteller</th><th>Kategorie</th><th>Rasse</th><th>Farbenschlag</th><th>Geschlecht</th><th>Alter</th><th>Ringnummer</th><th>Status</th><th/></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td>{a.catalog_number??a.cage_number??"–"}</td><td>{a.exhibitor_number??"–"}</td><td>{a.exhibitor_name}</td><td>{a.category}</td><td>{a.breed}</td><td>{a.color}</td><td>{a.sex}</td><td>{a.age_class}</td><td>{a.ring_number||"–"}</td><td><Status>{a.status}</Status></td><td><Link className="icon-button" href={`/tiermeldungen/${a.id}/bearbeiten`} title="Bearbeiten"><Pencil size={15}/></Link></td></tr>)}</tbody></table></div></div>}
  </>;
}
