"use server";
import { cookies } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { ACTIVE_CLUB_COOKIE,assertAnimalBelongsToClub,assertExhibitorBelongsToClub,assertShowBelongsToClub,getClubActor } from "@/lib/club-context";
import { getSql } from "@/lib/db";
import { logDatabaseError } from "@/lib/database-error";

const text=z.string().trim().min(1,"Pflichtfeld").max(300),optional=z.string().trim().max(500).default(""),uuid=z.string().uuid(),email=z.union([z.literal(""),z.string().email("Ungültige E-Mail-Adresse")]);
const value=(data:FormData,key:string)=>String(data.get(key)??"");
function fail(operation:string,error:unknown):never{if(error instanceof z.ZodError)throw new Error(error.issues[0]?.message??"Bitte Eingaben prüfen.");logDatabaseError(operation,error);throw error}
const refresh=()=>{revalidatePath("/");revalidatePath("/vereine");revalidatePath("/ausstellungen");revalidatePath("/aussteller");revalidatePath("/tiermeldungen")};

export async function selectActiveClub(data:FormData){const clubId=uuid.parse(value(data,"clubId"));const rows=await getSql()`SELECT id FROM clubs WHERE id=${clubId} AND active=true`;if(!rows[0])throw new Error("Dieser Verein ist nicht aktiv oder existiert nicht.");const store=await cookies();store.set(ACTIVE_CLUB_COOKIE,clubId,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge:60*60*24*30});redirect("/")}
export async function deactivateClub(data:FormData){const clubId=uuid.parse(value(data,"id"));await getSql()`UPDATE clubs SET active=false,updated_at=now() WHERE id=${clubId}`;const store=await cookies();if(store.get(ACTIVE_CLUB_COOKIE)?.value===clubId)store.delete(ACTIVE_CLUB_COOKIE);refresh();redirect("/vereine")}

const clubSchema=z.object({name:text,shortName:text.max(30),street:optional,postalCode:optional,city:optional,contactPerson:optional,email,phone:optional,logoUrl:z.union([z.literal(""),z.string().url("Ungültige Logo-URL")])});
export async function saveClub(data:FormData){let id=value(data,"id");try{const v=clubSchema.parse({name:value(data,"name"),shortName:value(data,"shortName"),street:value(data,"street"),postalCode:value(data,"postalCode"),city:value(data,"city"),contactPerson:value(data,"contactPerson"),email:value(data,"email"),phone:value(data,"phone"),logoUrl:value(data,"logoUrl")});const sql=getSql();if(id){uuid.parse(id);await sql`UPDATE clubs SET name=${v.name},short_name=${v.shortName},street=${v.street},postal_code=${v.postalCode},city=${v.city},contact_name=${v.contactPerson},email=${v.email},phone=${v.phone},logo_url=${v.logoUrl||null},updated_at=now() WHERE id=${id}`}else{const rows=await sql`INSERT INTO clubs(name,short_name,street,postal_code,city,contact_name,email,phone,logo_url,active) VALUES(${v.name},${v.shortName},${v.street},${v.postalCode},${v.city},${v.contactPerson},${v.email},${v.phone},${v.logoUrl||null},true) RETURNING id`;id=String(rows[0].id)}}catch(error){fail("clubs.save",error)}refresh();redirect(`/vereine/${id}`)}

const showSchema=z.object({title:text,venue:text,venueStreet:optional,venuePostalCode:optional,venueCity:optional,startsAt:z.iso.date(),endsAt:z.iso.date(),deadline:z.iso.date(),status:text,description:optional}).refine(v=>v.endsAt>=v.startsAt,{message:"Das Ende darf nicht vor dem Beginn liegen."});
export async function saveExhibition(data:FormData){const actor=await getClubActor();let id=value(data,"id");try{const v=showSchema.parse({title:value(data,"title"),venue:value(data,"venue"),venueStreet:value(data,"venueStreet"),venuePostalCode:value(data,"venuePostalCode"),venueCity:value(data,"venueCity"),startsAt:value(data,"startsAt"),endsAt:value(data,"endsAt"),deadline:value(data,"deadline"),status:value(data,"status"),description:value(data,"description")});const sql=getSql();if(id){uuid.parse(id);await assertShowBelongsToClub(id,actor.clubId);await sql`UPDATE shows SET name=${v.title},venue_name=${v.venue},venue_street=${v.venueStreet},venue_postal_code=${v.venuePostalCode},venue_city=${v.venueCity},show_start=${v.startsAt},show_end=${v.endsAt},registration_deadline=${v.deadline},status=${v.status},subtitle=${v.description},updated_at=now() WHERE id=${id} AND club_id=${actor.clubId}`}else{const rows=await sql`INSERT INTO shows(club_id,name,venue_name,venue_street,venue_postal_code,venue_city,show_start,show_end,registration_deadline,status,subtitle) VALUES(${actor.clubId},${v.title},${v.venue},${v.venueStreet},${v.venuePostalCode},${v.venueCity},${v.startsAt},${v.endsAt},${v.deadline},${v.status},${v.description}) RETURNING id`;id=String(rows[0].id)}}catch(error){fail("shows.save",error)}refresh();redirect("/ausstellungen")}

const exhibitorSchema=z.object({showId:uuid,firstName:text,lastName:text,street:optional,postalCode:optional,city:optional,email,phone:optional,associationName:optional,ageGroup:optional});
export async function saveExhibitor(data:FormData){const actor=await getClubActor();let id=value(data,"id");try{const v=exhibitorSchema.parse({showId:value(data,"showId"),firstName:value(data,"firstName"),lastName:value(data,"lastName"),street:value(data,"street"),postalCode:value(data,"postalCode"),city:value(data,"city"),email:value(data,"email"),phone:value(data,"phone"),associationName:value(data,"associationName"),ageGroup:value(data,"ageGroup")});await assertShowBelongsToClub(v.showId,actor.clubId);const sql=getSql();if(id){uuid.parse(id);await assertExhibitorBelongsToClub(id,actor.clubId);await sql`UPDATE exhibitors SET show_id=${v.showId},first_name=${v.firstName},last_name=${v.lastName},street=${v.street},postal_code=${v.postalCode},city=${v.city},email=${v.email},phone=${v.phone},exhibitor_club_name=${v.associationName},age_group=${v.ageGroup||null},updated_at=now() WHERE id=${id}`}else{const rows=await sql`INSERT INTO exhibitors(show_id,first_name,last_name,street,postal_code,city,email,phone,exhibitor_club_name,age_group) VALUES(${v.showId},${v.firstName},${v.lastName},${v.street},${v.postalCode},${v.city},${v.email},${v.phone},${v.associationName},${v.ageGroup||null}) RETURNING id`;id=String(rows[0].id)}}catch(error){fail("exhibitors.save",error)}refresh();redirect(`/aussteller/${id}`)}

const animalSchema=z.object({exhibitionId:uuid,exhibitorId:uuid,breedVariantId:uuid,species:text,sex:text,ageClass:optional,ringNumber:text,cageNumber:optional,entryFee:z.coerce.number().min(0).max(999999),status:text});
export async function saveEntry(data:FormData){const actor=await getClubActor();try{const id=value(data,"id");const v=animalSchema.parse({exhibitionId:value(data,"exhibitionId"),exhibitorId:value(data,"exhibitorId"),breedVariantId:value(data,"breedVariantId"),species:value(data,"species"),sex:value(data,"sex"),ageClass:value(data,"ageClass"),ringNumber:value(data,"ringNumber"),cageNumber:value(data,"cageNumber"),entryFee:value(data,"entryFee"),status:value(data,"status")});await Promise.all([assertShowBelongsToClub(v.exhibitionId,actor.clubId),assertExhibitorBelongsToClub(v.exhibitorId,actor.clubId)]);const sql=getSql();if(id){uuid.parse(id);await assertAnimalBelongsToClub(id,actor.clubId);const rows=await sql`SELECT entry_id FROM animals WHERE id=${id}`;const entryId=uuid.parse(String(rows[0]?.entry_id));await Promise.all([sql`UPDATE animals SET show_id=${v.exhibitionId},breed_color_variant_id=${v.breedVariantId},entry_type=${v.species},sex=${v.sex},age_class=${v.ageClass||null},ring_number=${v.ringNumber},cage_number=${v.cageNumber||null},updated_at=now() WHERE id=${id}`,sql`UPDATE entries SET show_id=${v.exhibitionId},exhibitor_id=${v.exhibitorId},status=${v.status},total_amount=${v.entryFee},updated_at=now() WHERE id=${entryId}`])}else{const entries=await sql`INSERT INTO entries(show_id,exhibitor_id,status,total_amount) VALUES(${v.exhibitionId},${v.exhibitorId},${v.status},${v.entryFee}) RETURNING id`;const entryId=String(entries[0].id);await sql`INSERT INTO animals(entry_id,show_id,breed_color_variant_id,entry_type,sex,age_class,ring_number,cage_number,withdrawn) VALUES(${entryId},${v.exhibitionId},${v.breedVariantId},${v.species},${v.sex},${v.ageClass||null},${v.ringNumber},${v.cageNumber||null},false)`}}catch(error){fail("animals.save",error)}refresh();redirect("/tiermeldungen")}

export async function deleteEntity(data:FormData){const actor=await getClubActor();const kind=z.enum(["club","exhibition","exhibitor","entry"]).parse(value(data,"kind")),id=uuid.parse(value(data,"id")),sql=getSql();try{if(kind==="club")throw new Error("Vereine werden in der Betreiberverwaltung deaktiviert.");if(kind==="exhibition"){await assertShowBelongsToClub(id,actor.clubId);await sql`DELETE FROM shows WHERE id=${id} AND club_id=${actor.clubId}`}if(kind==="exhibitor"){await assertExhibitorBelongsToClub(id,actor.clubId);await sql`DELETE FROM exhibitors WHERE id=${id}`}if(kind==="entry"){await assertAnimalBelongsToClub(id,actor.clubId);const rows=await sql`DELETE FROM animals WHERE id=${id} RETURNING entry_id`;if(rows[0])await sql`DELETE FROM entries WHERE id=${String(rows[0].entry_id)} AND NOT EXISTS(SELECT 1 FROM animals WHERE entry_id=${String(rows[0].entry_id)})`}}catch(error){fail(`${kind}.delete`,error)}refresh()}
