import Link from "next/link";
import { redirect } from "next/navigation";
import { Bird,CalendarDays,LogIn,Plus,ShieldCheck,UserPlus,Users } from "lucide-react";
import { getViewerSession } from "@/lib/club-context";
import { getDashboardData } from "@/lib/data";
import { PageHeader,Status } from "@/components/ui";
export const dynamic="force-dynamic";

function PublicHome(){return <div className="public-home"><span className="brand-mark"><Bird size={24}/></span><h1>Ausstellungen gemeinsam organisieren</h1><p>Der geschützte Vereinsbereich für Ausstellungen, Aussteller und Tiermeldungen.</p><div className="public-home-actions"><Link className="button primary" href="/verein-login"><LogIn size={17}/>Vereinslogin</Link><Link className="button secondary" href="/verein-registrieren"><UserPlus size={17}/>Verein registrieren</Link></div><Link className="operator-entry" href="/betreiber-login"><ShieldCheck size={14}/>Betreiberzugang</Link></div>}

export default async function Dashboard(){const session=await getViewerSession();if(!session)return <PublicHome/>;if(session.isOperator)redirect("/betreiber");const club=session.club,{counts,exhibitions}=await getDashboardData(club.id),cards=[{label:"Ausstellungen",value:counts.exhibitions,icon:CalendarDays},{label:"Aussteller",value:counts.exhibitors,icon:Users},{label:"Tiermeldungen",value:counts.entries,icon:Bird}];return <><PageHeader title="Übersicht" description={`Kennzahlen und Aufgaben für ${club.name}`}/><section className="stats club-stats">{cards.map(({label,value,icon:Icon})=><div className="stat-card" key={label}><span className="stat-icon"><Icon size={21}/></span><div><strong>{value}</strong><span>{label}</span></div></div>)}</section><section className="dashboard-grid"><div className="panel"><h2>Schnellaktionen</h2><div className="quick-actions"><Link className="quick" href="/ausstellungen/neu"><Plus size={19}/>Neue Ausstellung</Link><Link className="quick" href="/aussteller/neu"><UserPlus size={19}/>Neuer Aussteller</Link><Link className="quick" href="/tiermeldungen/neu"><Bird size={19}/>Neue Tiermeldung</Link></div></div><div className="panel"><h2>Nächste Ausstellungen</h2><div className="next-list">{exhibitions.slice(0,3).map(e=><div className="next-item" key={e.id}><div><strong>{e.title}</strong><span>{e.venue} · {new Date(e.starts_at).toLocaleDateString("de-DE")}</span></div><Status>{e.status}</Status></div>)}{exhibitions.length===0?<span className="sub">Noch keine Ausstellungen angelegt.</span>:null}</div></div></section></>}
