"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bird,Building2,CalendarDays,ClipboardList,LayoutDashboard,LogIn,LogOut,ShieldCheck,SlidersHorizontal,UserPlus,Users,X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useState } from "react";
import { logout } from "@/app/actions";

type NavItem={href:string;label:string;icon:LucideIcon;exact?:boolean};
const clubLinks:NavItem[]=[{href:"/",label:"Übersicht",icon:LayoutDashboard},{href:"/ausstellungen",label:"Ausstellungen",icon:CalendarDays},{href:"/aussteller",label:"Aussteller",icon:Users},{href:"/tiermeldungen",label:"Tiermeldungen",icon:Bird}];
const operatorLinks:NavItem[]=[{href:"/betreiber",label:"Betreiberübersicht",icon:LayoutDashboard,exact:true},{href:"/betreiber/vereine",label:"Vereine",icon:Building2},{href:"/betreiber/status",label:"Statusverwaltung",icon:SlidersHorizontal}];
const planned=["B-Bögen","Katalog","Bewertungen","Abrechnung"];
type Props={viewer:{clubName:string;email:string;isOperator:boolean}|null};
export function Sidebar({viewer}:Props){const path=usePathname(),[open,setOpen]=useState(false);if(!viewer)return <header className="public-nav"><Link className="public-brand" href="/"><Bird size={20}/>Ausstellungsmanager</Link><nav><Link href="/verein-login"><LogIn size={16}/>Vereinslogin</Link><Link className="button primary" href="/verein-registrieren"><UserPlus size={16}/>Verein registrieren</Link><Link className="operator-nav-link" href="/betreiber-login">Betreiber</Link></nav></header>;const links=viewer.isOperator?operatorLinks:clubLinks;return <><button className="mobile-menu" onClick={()=>setOpen(true)} aria-label="Navigation öffnen">☰</button>{open?<button className="scrim" onClick={()=>setOpen(false)} aria-label="Navigation schließen"/>:null}<aside className={`sidebar ${open?"open":""}`}><div className="brand"><span className="brand-mark">{viewer.isOperator?<ShieldCheck size={22}/>:<Bird size={22}/>}</span><span><strong>Ausstellungsmanager</strong><small>{viewer.isOperator?"Betreiberverwaltung":"Vereinsbereich"}</small></span><button className="close-menu" onClick={()=>setOpen(false)} aria-label="Navigation schließen"><X/></button></div><div className="club-context"><small>{viewer.isOperator?"Betreiber":"Angemeldeter Verein"}</small><strong>{viewer.isOperator?viewer.email:viewer.clubName}</strong></div><nav>{links.map(({href,label,icon:Icon,...item})=>{const active=item.exact?path===href:(href==="/"?path===href:path.startsWith(href));return <Link key={href} href={href} onClick={()=>setOpen(false)} className={active?"active":""}><Icon size={19}/>{label}</Link>})}{!viewer.isOperator?<><span className="nav-section">Später verfügbar</span>{planned.map(label=><span className="planned-nav" key={label}><ClipboardList size={17}/>{label}</span>)}</>:null}</nav><form action={logout} className="sidebar-logout"><button><LogOut size={17}/>Abmelden</button></form><div className="sidebar-foot"><span className="status-dot"/>System bereit<small>Neon PostgreSQL</small></div></aside></>}
